swagger: '2.0'
post:
  description: Endpoint to classify input text using MLP Classifier Model
  version: '1.0.0'
  title: Input text
host: localhost:5000
basepath: '/'
schemes:
  - http
paths:
/upload_nn:
post:
tags:
  - name: Processing Input
summary: Text classification from uploaded file using MLP Classifier Model
consumes:
  - multipart/form-data
parameters:
  - name: text
    in: formData
    description: The text to classify
    required: true
    type: string
responses:
  '200':
    description: Text classified successfully
    schema:
    type: object
    properties:
    message:
    type: string
    text:
    type: string
    sentiment:
    type: string
  '400':
    description: Error in model loading
    schema:
    type: object
    properties:
    error:
    type: string
  '500':
    description: Server error
    schema:
    type: object
    properties:
    error:
    type: string
